// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password.proto

package ie.gmit.ds;

public interface ValidatePasswordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ie.gmit.ds.ValidatePassword)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string hashedPassword = 2;</code>
   */
  java.lang.String getHashedPassword();
  /**
   * <code>string hashedPassword = 2;</code>
   */
  com.google.protobuf.ByteString
      getHashedPasswordBytes();

  /**
   * <code>string salt = 3;</code>
   */
  java.lang.String getSalt();
  /**
   * <code>string salt = 3;</code>
   */
  com.google.protobuf.ByteString
      getSaltBytes();
}
