// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password.proto

package ie.gmit.ds;

public interface ValidateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ie.gmit.ds.Validate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool passwordValid = 1;</code>
   */
  boolean getPasswordValid();
}
